maxFieldSize: 50

1: &trampoline
  shop:
    priceRuby: 100
    priceGold: 100
  behavior:
    type: trampoline
    width: 1
    length: 3
    rotated: false
    static:
      x: 3
      y: 3
  view:
    field: "trampoline.swf"
    shop: "otherFile.swf"
  descriptions:
    ru:
      name: "Обычный трамплин"
      desc: "Понравится начинающим"
    en:
      name: "Simple trampoline"
      desc: "Will like for beginners"

0: &decor
  shop:
    priceRuby: 100
    priceGold: 100
  behavior:
    type: decor
    width: 1
    length: 1
    rotated: true
  view:
    field: "decor.swf"
    shop: "otherFile.swf"
  descriptions:
      ru:
        name: "Плакат с символикой парка"
        desc: "Хороший плакат, расскажет посетителям о том где они находятся"
      en:
        name: "Poster with park logo"
        desc: "Good poster, tell to riders about park"

2: &rail
  shop:
    priceRuby: 100
    priceGold: 100
  behavior:
    type: rail
    width: 1
    length: 2
    rotated: true
  view:
    field: "rail.swf"
    shop: "otherFile.swf"
  descriptions:
        ru:
          name: "Обычный рэйл"
          desc: "Понравится начинающим"
        en:
          name: "Simple rail"
          desc: "Will like for beginners"

4: &tree
  shop:
    priceRuby: 100
    priceGold: 100
  behavior:
    type: rail
    width: 1
    length: 2
    rotated: true
  view:
    field: "tree.swf"
    shop: "otherFile.swf"
  descriptions:
        ru:
          name: "Дерево"
          desc: "Понравится начинающим"
        en:
          name: "Tree"
          desc: "Will like for beginners"

1000: &rider
  shop:
    priceRuby: 100
    priceGold: 100
  behavior:
    components:
      - name: rider
        speed: 3 #unit/s
      - name: move
      - name: alongRotation
      - name: simpleAnimation
        fps: 10
    width: 1
    length: 2
    rotated: true
  view:
    field: "rider.swf"
    shop: "otherFile.swf"
  descriptions:
        ru:
          name: "Начинающий райдер"
          desc: "Понравится начинающим"
        en:
          name: "Beginner rider"
          desc: "Will like for beginners"
